### ISSUE TITLE
Question: Adding support for ITE8951 based E-Ink Displays, M5 Paper and EPDIY ?

### ISSUE THREAD

**Issue by markbirss** [codewitch-honey-crisis/gfx#1]
Hi

I just noticed your current selection of e-ink displays and wanted to ask if you had thought of possibly adding support for the ITE8951 based displays ie WaveShare and GoodDisplay ITE8951 HAT or M5 Paper (ITE8951) and the other EPDIY supported displays

ITE8951 displays can also be used over SPI, but also requires a MISO pin to read the display eeprom

e.g using GxEPD2 on 9.7 inch via the HAT

`WaveShare 9.7HAT
________________
setup
⸮init reset_to_ready : 1692002
GetIT8951SystemInfo : 214000
Panel(W,H) = (1200,825)

Image Buffer Address = 11A1E0

FW Version = SWv_0.2.1T

LUT Version = M841

_IT8951SetVCOM : 411969
_IT8951GetVCOM : 6896
VCOM = -1.50V
VCOM = -1.50V
_PowerOn : 1
refresh cmd : 6517
refresh : 737000
refresh cmd : 5926
refresh : 506000
_PowerOff : 214000`

EPDIY
https://github.com/vroland/epdiy

The LilyGo 4.7 is based on V_Rolands EPDIY board at a earlier version

**Comment by codewitch-honey-crisis** [comment]
I have added support for the Lilygo T5 4.7lib_deps = codewitch-honey-crisis/htcw_lilygot54in7@^0.9.2 I can add support for the devices you listed once I buy them. I’ll add them to my purchase list. Sent from Mail for Windows From: Mark Trevor BirssSent: Sunday, March 27, 2022 3:35 PMTo: codewitch-honey-crisis/gfxCc: SubscribedSubject: [codewitch-honey-crisis/gfx] Question: Adding support for ITE8951 based E-Ink Displays, M5 Paper and EPDIY ? (Issue #1) HiI just noticed your current selection of e-ink displays and wanted to ask if you had thought of possibly adding support for the ITE8951 based displays ie WaveShare and GoodDisplay ITE8951 HAT or M5 Paper (ITE8951) and the other EPDIY supported displaysITE8951 displays can also be used over SPI, but also requires a MISO pin to read the display eeprome.g using GxEPD2 on 9.7 inch via the HAT`WaveShare 9.7HATsetup⸮init reset_to_ready : 1692002GetIT8951SystemInfo : 214000Panel(W,H) = (1200,825)Image Buffer Address = 11A1E0FW Version = SWv_0.2.1TLUT Version = M841_IT8951SetVCOM : 411969_IT8951GetVCOM : 6896VCOM = -1.50VVCOM = -1.50V_PowerOn : 1refresh cmd : 6517refresh : 737000refresh cmd : 5926refresh : 506000_PowerOff : 214000`EPDIYhttps://github.com/vroland/epdiyThe LilyGo 4.7 is based on V_Rolands EPDIY board at a earlier version—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by codewitch-honey-crisis** [comment]
Sorry about my last response. Looks like I can't use my mail client to respond.

I've investigated this display. I can support it, but it's quite expensive so I won't be adding support for it right away. It's tough to justify to my husband spending that for a display for a hobby project, but I will make it happen as soon as I can. =)

**Comment by markbirss** [comment]
@codewitch-honey-crisis 

No problem, thank you for your response and I can most certainly understand.
