### ISSUE TITLE
Does gfx support *.fon used by Windows 3.1?

### ISSUE THREAD

**Issue by shaovoon** [codewitch-honey-crisis/gfx#38]
It isn't clear from the source code that if the library support displaying *.fon fonts. I vaguely remember you mentioned that before on CodeProject but that website is defunct.

Does gfx support *.fon format used by Windows 3.1?

**Comment by codewitch-honey-crisis** [comment]
Yes, it supports raster .FON but not their "vector" .FON format
The documentation is a bit out of date now that 2.0 is released, but a lot is still the same:
https://honeythecodewitch.com/gfx
I should note that 2.0 removes actual display drivers, and works a lot like LVGL in that it expects you to implement the last mile of sending data to the display.
Because of that, I recommend using [htcw_uix](https://github.com/codewitch-honey-crisis/uix) with it. They work in tandem. UIX is a draw on demand framework. You place "controls" on a screen, and each control knows how to draw itself. UIX uses dirty rectangle algos, and generates bitmaps of portions of the screen that need to be refreshed, again like LVGL. It really helps.

**Comment by codewitch-honey-crisis** [comment]
If you have any further questions, feel free to reopen this thread.
